### ISSUE TITLE
Search by barcode

### ISSUE THREAD

**Issue by blackboxlogic** [ilyalatt/Discogs.ApiClient#1]
Context:
I'm trying to search Discogs by barcode and I'm having trouble using `DatabaseSearchParams` since its constructor requires the `query` parameter to be passed in. In my case, I don't think I want any query parameter, I only want to set the `barcode` property. I tried passing an empty string to the constructor, but the search unexpectedly yielded no results.
Question:
How can I search by just barcode?

```
var credentials = Discogs.ApiClient.DiscogsApiClientCredentials.FromToken(key);
var environment = Discogs.ApiClient.DiscogsApiClientEnvironment.CreateDefault(credentials);
var client = Discogs.ApiClient.DiscogsApiClient.Create(environment);

var db = client.Database;
var task = db.Search(new Discogs.ApiClient.ApiModel.Dto.Requests.Database.DatabaseSearchParams("???") { Barcode = "060768320925" });
var result = task.Result;
```

**Comment by ilyalatt** [comment]
Hi! There were 2 problems.
The first problem is that `Query` is required. It is not necessary so I have added a default constructor.
The second problem is that `Type` was `Artist` by default.
So now you can search via `new DatabaseSearchParams { Barcode = "060768320925" }` and it should work. It is fixed in the version `0.2.1`.
